# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Linpad Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pillow  # Include Pillow since you're using it
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest

    - name: Package Application
      run: |
        # Install additional packages if necessary
        sudo apt-get install -y python3-tk  # Install Tkinter if needed
        # Create the .deb package
        mkdir -p package/DEBIAN
        echo "Package: linpad" >> package/DEBIAN/control
        echo "Version: 1.0" >> package/DEBIAN/control
        echo "Section: utils" >> package/DEBIAN/control
        echo "Priority: optional" >> package/DEBIAN/control
        echo "Architecture: all" >> package/DEBIAN/control
        echo "Depends: python3, python3-tk, python3-pil" >> package/DEBIAN/control
        echo "Maintainer: Your Name <your.email@example.com>" >> package/DEBIAN/control
        echo "Description: Linpad is a simple text editor with syntax highlighting and word count functionality." >> package/DEBIAN/control
        echo "I'm going to make this open source via GitHub, so everyone can work in this file to make its functionality so rich." >> package/DEBIAN/control
        echo "Let me know if you have some good ideas to make it better." >> package/DEBIAN/control
        # Copy the application files
        cp -r ./path/to/your/application/* package/
        # Build the package
        dpkg-deb --build package
